# Generated by Django 6.0.4 on 2026-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('field_of_study', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
