# Generated by Django 6.0.4 on 2026-04-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='student123', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(unique=True),
        ),
    ]
